version: '3.8'

services:
  onbongo-easypanel:
    build:
      context: .
      dockerfile: Dockerfile.easypanel
    container_name: onbongo-easypanel
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
